### PR TITLE
PASS1-475: Comply with pycodestyle@2.9.0.

### PR DESCRIPTION
**Pull request by jeandudey**

### CODE REVIEW

**Comment by FoundationKen** [comment]
I don't like this "space after assert" change.  Can we change the config to leave that as is?  The other changes are fine. @jeandudey

**Comment by jeandudey** [comment]
>I don't like this "space after assert" change.

Yeah we can suppress the error.

**Comment by jeandudey** [comment]
Misclick

**Comment by jeandudey** [comment]
@FoundationKen updated and switched back to pip version to catch future errors.

**Review by FoundationKen — APPROVED** [review]

**Review by FoundationKen — APPROVED** [review]

**Pull request merged**
